### ISSUE TITLE
tsb

### ISSUE THREAD

**Issue by 20ch** [cracklua/cracks#4]
could u deobfuscate the tsb gojo script ?

**Comment by cracklua** [comment]
I dont deobfuscate stuff

**Comment by atomiciscool** [comment]
can't u give like the not obfuscated version 😭 
cause rn its broken too

**Comment by cracklua** [comment]
if its broken then execute the obfuscated source code instead of the loadstring

**Comment by atomiciscool** [comment]
> if its broken then execute the obfuscated source code instead of the loadstring

no i mean the script is broken on itself, when you execute it you get 99 errors in the console lmao

**Comment by cracklua** [comment]
if it doesnt work at all then thats caused by your executor, consider switching
